name: movie_search_app
description: A movie search application using IMDB API
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  video_player: ^2.7.0
  google_fonts: ^5.1.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
